stages:
  - master:
      pre:
        - sh: make -C tools prep-root
      config_file:
        port: $MASTER_PORT_FROM_INTERNAL
        db:
          host: 0.0.0.0
          port: 5432
          password: postgres
          user: postgres
          name: determined
        checkpoint_storage:
          type: gcs
          bucket: $GCS_BUCKET
          save_experiment_best: 0
          save_trial_best: 1
          save_trial_latest: 1
        log:
          level: debug
        root: tools/build
        cache:
          cache_dir: /tmp/determined-cache
        launch_error: false
        security:
          tls:
            cert: $MASTER_TLS_CERT
            key: $MASTER_TLS_KEY
        resource_manager:
          type: kubernetes
          namespace: $KUBERNETES_NAMESPACE
          slot_type: "cpu"
          max_slots_per_pod: 1
          slot_resource_requests:
            cpu: 1
          default_aux_resource_pool: default
          default_compute_resource_pool: default
          _master_ip: $MASTER_IP_FROM_INTERNAL
          _master_port: $MASTER_PORT_FROM_INTERNAL
          _use_user_kubeconfig: true
        resource_pools:
          - pool_name: default
            scheduler:
              type: priority
