apiVersion: batch/v1
kind: Job
metadata:
  name: 
spec:
  template:
    spec:
      containers:
      - name: gke-cleanup
        image: determinedai/det-ci-images:.{{ .Values.version }}
        imagePullPolicy: "Always"
      restartPolicy: Never
  backoffLimit: 4
