commands:
  p: make -C harness clean build  # rebuild Python
  w: make -C webui build          # rebuild Webui
  c: make -C docs build           # rebuild doCs

stages:
  - db:
      port: 5432
      db_name: determined
      password: postgres
      container_name: determined_db
      image_name: "postgres:10.14"
      data_dir: ~/.postgres

  - custom:
      pre:
        #- sh: minikube start --profile defaultrm
        - sh: kubectl --context defaultrm apply -f tools/k8s/my-service-account.yaml
      name: creds-default
      cmd:
        - tools/k8s/fetch-creds.sh
        - --context
        - defaultrm
        - /tmp/det-creds-default
        - my-service-account
      post:
        - logcheck:
            regex: successfully fetched initial token

  - custom:
      pre:
        #- sh: minikube start --profile additionalrm
        - sh: kubectl --context additionalrm apply -f tools/k8s/my-service-account.yaml
      name: creds-additionalrm
      cmd:
        - tools/k8s/fetch-creds.sh
        - --context
        - defaultrm
        - /tmp/det-creds-additional
        - my-service-account
      post:
        - logcheck:
            regex: successfully fetched initial token

  - master:
      pre:
        - sh: make -C proto build
        - sh: make -C master build
        - sh: make -C tools prep-root
        - sh: mkdir -p /tmp/determined-cp
      post:
        - logcheck:
            regex: accepting incoming connections on port
      cmdline:
        - master/build/determined-master
        - --config-file
        - :config

      config_file:
        db:
          host: localhost
          port: 5432
          password: postgres
          user: postgres
          name: determined
        checkpoint_storage:
          type: shared_fs
          host_path: /tmp/determined-cp
        cache:
          cache_dir: /tmp/determined-cache
        log:
          level: debug
        enable_cors: true
        root: tools/build

        resource_manager:
          type: kubernetes
          namespace: default
          max_slots_per_pod: 1
          slot_type: "cpu"
          slot_resource_requests:
            cpu: 1
          # Special settings for running determined-master outside of k8s:
          _creds_dir: /tmp/det-creds-default
          _master_ip: $DOCKER_LOCALHOST
          _master_port: 8080
        additional_resource_managers:
        - resource_manager:
            type: kubernetes
            name: additionalrm
            namespace: default
            max_slots_per_pod: 1
            slot_type: "cpu"
            slot_resource_requests:
              cpu: 1
            _creds_dir: /tmp/det-creds-additional
            _master_ip: $DOCKER_LOCALHOST
            _master_port: 8080
