commands:
  p: make -C harness clean build  # rebuild Python
  w: make -C webui build          # rebuild Webui
  c: make -C docs build           # rebuild doCs

stages:
  - db:
      port: 5432
      db_name: determined
      password: postgres
      container_name: determined_db
      image_name: "postgres:10.14"
      data_dir: ~/.postgres

  - master:
      pre:
        - sh: make -C ../../proto build
        - sh: make -C ../../master build
        - sh: make -C ../../tools prep-root
      post:
        - logcheck:
            regex: accepting incoming connections on port
      # env:
      #   ALL_PROXY: $SOCKS5_PROXY_URL
      #   HTTP_PROXY: $SOCKS5_PROXY_URL
      #   HTTPS_PROXY: $SOCKS5_PROXY_URL

      cmdline:
        - ../../master/build/determined-master
        - --config-file
        - :config

      config_file:
        port: $MASTER_PORT_FROM_INTERNAL
        db:
          host: localhost
          port: 5432
          password: postgres
          user: postgres
          name: determined
        checkpoint_storage:
          type: gcs
          bucket: $GCS_BUCKET
          save_experiment_best: 0
          save_trial_best: 1
          save_trial_latest: 1
        cache:
          cache_dir: /tmp/determined-cache
        log:
          level: debug
        enable_cors: true
        root: ../../tools/build

        resource_manager:
          type: kubernetes
          namespace: $KUBERNETES_NAMESPACE
          max_slots_per_pod: 1
          slot_type: "cpu"
          slot_resource_requests:
            cpu: 1
          _master_ip: $MASTER_IP_FROM_INTERNAL
          _master_port: $MASTER_PORT_FROM_INTERNAL
          _use_user_kubeconfig: true
        security:
          tls:
            cert: $MASTER_TLS_CERT
            key: $MASTER_TLS_KEY
